# Generated by Django 3.2.16 on 2025-02-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPerumahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perumahan', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('rt', models.CharField(max_length=5)),
                ('rw', models.CharField(max_length=5)),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('alamat_maps', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPenduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_blok', models.CharField(max_length=10)),
                ('nama_kk', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pemilik tetap', 'Pemilik Tetap'), ('kosong', 'Kosong')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('perumahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.masterperumahan')),
            ],
        ),
    ]
