# Generated by Django 3.2.16 on 2025-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250224_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpenduduk',
            name='no_blok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterperumahan',
            name='rt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterperumahan',
            name='rw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
