# Generated by Django 3.2.16 on 2025-02-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250228_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='masterperumahan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterperumahan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kabupaten')),
            ],
        ),
        migrations.AlterField(
            model_name='masterperumahan',
            name='kabupaten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.kabupaten'),
        ),
        migrations.AlterField(
            model_name='masterperumahan',
            name='kecamatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.kecamatan'),
        ),
    ]
