# Generated by Django 3.2.16 on 2025-03-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250228_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPenyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=255)),
                ('tgl_mulai_sewa', models.DateField()),
                ('tgl_terakhir_sewa', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Tidak Aktif'), (1, 'Aktif')], default=1)),
                ('penduduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.masterpenduduk')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAnggotaKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ayah', 'Ayah'), ('ibu', 'Ibu'), ('anak', 'Anak')], max_length=10)),
                ('tgl_lahir', models.DateField()),
                ('penduduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.masterpenduduk')),
            ],
        ),
    ]
