# Generated by Django 3.2.16 on 2025-03-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_masteranggotakeluarga_masterpenyewa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpenyewa',
            name='nama_penyewa',
        ),
        migrations.AlterField(
            model_name='masteranggotakeluarga',
            name='status',
            field=models.CharField(choices=[('ayah', 'Ayah'), ('ibu', 'Ibu'), ('anak', 'Anak'), ('saudara', 'Saudara')], max_length=10),
        ),
    ]
