# Generated by Django 3.2.16 on 2025-03-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20250306_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteranggotakeluarga',
            name='status',
            field=models.CharField(choices=[('ayah', 'Ayah'), ('ibu', 'Ibu'), ('anak', 'Anak'), ('saudara', 'Saudara'), ('lainnya', 'Lainnya')], max_length=10),
        ),
    ]
