# Generated by Django 3.2.16 on 2025-03-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_masteranggotakeluarga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteranggotakeluarga',
            name='penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_keluarga', to='home.masterpenduduk'),
        ),
        migrations.AlterField(
            model_name='masterpenyewa',
            name='penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penyewa', to='home.masterpenduduk'),
        ),
    ]
