# Generated by Django 3.2.16 on 2025-03-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20250306_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpenyewa',
            name='nama_penyewa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
