# Generated by Django 3.2.16 on 2025-04-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_masterpenyewa_nama_penyewa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pekerja', models.CharField(blank=True, max_length=255, null=True)),
                ('kode_petugas', models.CharField(blank=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Security', 'Security'), ('Petugas Kebersihan', 'Petugas Kebersihan'), ('Marbot', 'Marbot')], max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Tidak Aktif'), (1, 'Aktif')], default=1)),
                ('tgl_mulai_bekerja', models.DateField()),
            ],
        ),
    ]
