# Generated by Django 3.2.16 on 2025-04-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_masterpekerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, unique=True)),
                ('sumber_pemasukan', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Tidak Aktif'), (1, 'Aktif')], default=1)),
            ],
        ),
    ]
