# Generated by Django 3.2.16 on 2025-04-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.IntegerField(choices=[(0, 'Belum Lunas'), (1, 'Sudah Lunas')], default=1),
        ),
    ]
